In [2]:
import numpy as np

x = [1, 2, 3]
y = [8, 9, 10]

x + y 

[1, 2, 3, 8, 9, 10]

In [3]:
a = np.array(x) 
b = np.array(y)

a + b

array([ 9, 11, 13])

In [4]:
x * y 

TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
a * b   # поэлементное произведение 

array([ 8, 18, 30])

In [6]:
a @ b    # скалярное произведение 

56

In [8]:
a.dot(b) # скалярное произведение 

56

https://contest.yandex.ru/contest/25960/problems/

In [9]:
x = [i**2 for i in range(10**6)]
y = np.array(x)

## Задачка 1 (максимум перед нулем)

Реализуйте функцию, возвращающую максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой.

Например, для `x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])` ответом является 5. Если нулевых элементов нет, функция должна возвращать None.

In [11]:
%%timeit 
sum(x) 

6.12 ms ± 8.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
%%timeit 
np.sum(y)

112 µs ± 2.22 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [14]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [15]:
x == 0

array([False, False,  True, False,  True,  True, False, False,  True])

In [17]:
x[x > 0]

array([6, 2, 3, 5, 7])

In [20]:
x[x > 0].size

5

In [19]:
x[x > 0].shape

(5,)

In [26]:
x

array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [27]:
mask = np.hstack((False, x == 0))[:-1]
mask 

array([False, False, False,  True, False,  True,  True, False, False])

In [28]:
x[mask]

array([3, 0, 5])

In [29]:
x[mask].max()

5

In [30]:
def get_max_before_zero(x):
    mask = np.hstack((False, x == 0))[:-1]
    return x[mask].max()

get_max_before_zero(x)

5

## Задача 2  (про нормирование) 

У меня есть матрица $X$ из  равноверного распределения $U[-5; 5]$. Нужно отнормировать столбцы этой матрицы так, чтобы все они лежали на отрезке $[0;1]$. 

$$
x' = \frac{x - min(x)}{max(x) - min(x)}
$$


In [92]:
from scipy import stats 

uniform_rv = stats.uniform(-5, 10) # [-5; -5 + 10]
X = uniform_rv.rvs((100, 3))
X

array([[-3.34566251e+00,  4.41439176e-01,  3.30375628e+00],
       [ 1.77763986e+00, -1.56417684e+00,  7.12011892e-01],
       [-4.63100025e+00,  1.15222519e+00, -2.48757138e+00],
       [ 2.35044776e+00,  2.24063306e+00, -3.37142738e+00],
       [ 2.75252498e+00,  3.81269023e+00, -4.53034173e+00],
       [ 4.10199909e-01,  4.65222239e+00,  3.71087828e+00],
       [ 4.60925983e+00, -2.08567055e+00, -4.16456434e+00],
       [-3.98592440e-02, -2.14200621e+00, -2.46702773e+00],
       [ 3.17797225e+00, -2.30415789e+00, -2.96833538e+00],
       [-4.95010460e+00,  2.31407668e+00,  1.14456967e-01],
       [-4.51697144e+00,  4.07682113e+00,  3.21073179e+00],
       [ 2.64992686e+00, -3.76074796e+00, -3.81191552e+00],
       [-4.19046523e+00,  3.59262668e+00,  1.24128320e+00],
       [-1.01868123e+00, -1.16771952e+00, -1.70919084e+00],
       [-4.35009502e+00, -4.21239660e+00, -1.32057551e+00],
       [-9.19389555e-01,  2.87546030e+00,  4.01290920e+00],
       [ 2.54358095e+00, -3.36909654e+00

In [51]:
X[X > 0].sum()

374.80817018736957

In [57]:
X.size 

300

In [55]:
X.shape

(100, 3)

In [56]:
X.T.shape

(3, 100)

In [59]:
A = X.T @ X  # матричное умножение 
A

array([[ 764.77305312, -122.61117524,   10.51250332],
       [-122.61117524,  938.26428163,  141.3485118 ],
       [  10.51250332,  141.3485118 ,  811.43086714]])

In [60]:
np.linalg.det(A)

554303288.902452

In [61]:
np.linalg.eig(A)

EigResult(eigenvalues=array([1063.28988819,  653.68668359,  797.49163012]), eigenvectors=array([[-0.32513901,  0.6503206 ,  0.68656227],
       [ 0.83039746,  0.54370668, -0.12175014],
       [ 0.45246511, -0.53053384,  0.71680483]]))

In [62]:
np.linalg.svd(A)

SVDResult(U=array([[-0.32513901, -0.68656227, -0.6503206 ],
       [ 0.83039746,  0.12175014, -0.54370668],
       [ 0.45246511, -0.71680483,  0.53053384]]), S=array([1063.28988819,  797.49163012,  653.68668359]), Vh=array([[-0.32513901,  0.83039746,  0.45246511],
       [-0.68656227,  0.12175014, -0.71680483],
       [-0.6503206 , -0.54370668,  0.53053384]]))

In [64]:
X.mean()

0.04946563958135139

In [65]:
X.mean(axis=0)

array([-0.07309164, -0.04160657,  0.26309513])

In [66]:
X.mean(axis=1)

array([-1.45729558, -1.77584237, -0.01587372,  0.91177386, -1.37494525,
        0.094697  , -0.01073177, -0.63783273, -1.37816325, -1.0348264 ,
        2.23183392, -0.275346  , -0.48968618, -3.35893128, -1.39258334,
       -2.031307  , -0.53277825, -1.63277814,  1.08859569, -1.63659156,
        0.06024808,  0.1645294 , -1.54322704,  0.73790976, -0.66024076,
       -1.71611741, -2.33945894,  2.29628448,  0.43966696, -1.76513874,
        3.14242992, -1.41595092, -0.8768668 ,  2.18978427,  2.51252936,
        0.75017908,  3.58479503,  3.52130003,  0.46568354,  1.20109418,
       -1.76124557, -1.47671435, -2.67557552, -1.37126269,  0.83955469,
       -1.49546518,  1.90053569, -1.58228657,  0.52034415,  1.68273229,
        1.73053727,  1.92984942,  1.96387209,  2.13893018, -0.51449897,
       -2.19080018, -1.0040856 ,  0.09784938, -0.06418252,  2.92901812,
       -0.30640092,  2.20729277,  0.59537008, -0.98334115, -1.24886774,
        1.04408912, -2.17976603,  2.01156513, -0.90226893,  1.26

In [67]:
X.max(axis=0)

array([4.9542602 , 4.91032877, 4.97167448])

In [68]:
X.var(axis=0)

array([7.64238814, 9.38091171, 8.04508962])

In [70]:
a = np.array([1, 2, 3])  # просто вектор 
a


array([1, 2, 3])

In [71]:
a = np.array([[1, 2, 3]]) # вектор строка 
a


array([[1, 2, 3]])

In [72]:
a.shape 

(1, 3)

In [75]:
b = a.T  # вектор столбец
b

array([[1],
       [2],
       [3]])

In [77]:
A @ a # [3x3] пытаюсь умножить на [1x3]

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [78]:
A @ b # [3 x 3] пытаюсь умножить  на [3 x 1]

array([[ 551.0882126 ],
       [2177.96292343],
       [2727.50212836]])

In [80]:
np.linalg.matrix_rank(A)

3

In [82]:
A

array([[ 764.77305312, -122.61117524,   10.51250332],
       [-122.61117524,  938.26428163,  141.3485118 ],
       [  10.51250332,  141.3485118 ,  811.43086714]])

In [83]:
np.diag(A).sum() # это след матрица 

2514.4682018937037

In [84]:
# хочу найти обратную матрицу 

B = np.linalg.inv(A)
B

array([[ 1.33745769e-03,  1.82168176e-04, -4.90605307e-05],
       [ 1.82168176e-04,  1.11933297e-03, -1.97344099e-04],
       [-4.90605307e-05, -1.97344099e-04,  1.26740316e-03]])

In [85]:
A @ B 

array([[ 1.00000000e+00,  1.06842480e-18,  1.27343097e-19],
       [-1.12854977e-17,  1.00000000e+00,  7.04266589e-18],
       [-3.25711777e-18, -1.47785173e-17,  1.00000000e+00]])

In [86]:
0.3 - 0.1 

0.19999999999999998

In [87]:
0.3 - 0.1 == 0.2

False

In [91]:
np.sqrt( np.sum( (np.eye(3) - A @ B)**2 ) )

2.017753056532611e-17

У меня есть матрица $X$ из  равноверного распределения $U[-5; 5]$. Нужно отнормировать столбцы этой матрицы так, чтобы все они лежали на отрезке $[0;1]$. 

$$
x' = \frac{x - min(x)}{max(x) - min(x)}
$$


In [94]:
X.min(axis=0)

array([-4.98097885, -4.72015545, -4.90615628])

In [96]:
X.max(axis=0) - X.min(axis=0)

array([9.91803882, 9.43367313, 9.80765027])

In [103]:
X_scale = (X - X.min(axis=0))/(X.max(axis=0) - X.min(axis=0))
X_scale[:4]

array([[0.16488303, 0.5471458 , 0.83709271],
       [0.68144709, 0.33454399, 0.57283529],
       [0.03528708, 0.62249143, 0.24660187],
       [0.73920124, 0.7378662 , 0.15648283]])

In [102]:
X_scale.min(axis=0), X_scale.max(axis=0)

(array([0., 0., 0.]), array([1., 1., 1.]))

In [110]:
data = np.array([[80, 40, 150], [1.9, 1.5, 1.7], [0, 0, 1]]).T 
data  # первый столбик это вес, второй это рост, третий это наличие ожирения

array([[ 80. ,   1.9,   0. ],
       [ 40. ,   1.5,   0. ],
       [150. ,   1.7,   1. ]])

In [111]:
x_new = np.array([130, 2.1]) # метод ближайших соседей
X = data[:,:2]

In [118]:
r = np.sqrt( np.sum((X - x_new)**2, axis=1))
r

array([50.0004    , 90.00199998, 20.0039996 ])

In [120]:
np.argmin(r) # ну видимо у нашего чела тоже ожирение и надо гнать его по врачам

2

In [125]:
(150 - 130)**2, (2.1 -1.7)**2, (210 - 170)**2

(400, 0.16000000000000011, 1600)

In [126]:
X_scale = (X - X.min(axis=0))/(X.max(axis=0) - X.min(axis=0))
X_scale

array([[0.36363636, 1.        ],
       [0.        , 0.        ],
       [1.        , 0.5       ]])

In [129]:
x_new_scale = (x_new - X.min(axis=0))/(X.max(axis=0) - X.min(axis=0))

In [130]:
r = np.sqrt( np.sum((X_scale - x_new_scale)**2, axis=1))
r

array([0.6757304 , 1.70863147, 1.01639454])

In [131]:
np.argmin(r) # на самом деле ожирения нет и не надо никого гонять по врачам!

0

## Задача 3: 

Усложним предыдущую задачу! Дана матрица X и вектор v. Нужно найти в матрице X столбец, который будет ближе всего к вектору v.

In [136]:
X = np.random.binomial(100, 0.5, size=(5,3))/100
v = np.random.uniform(size=(5,1))
X, v

(array([[0.47, 0.44, 0.53],
        [0.37, 0.39, 0.53],
        [0.45, 0.53, 0.55],
        [0.46, 0.47, 0.46],
        [0.65, 0.51, 0.56]]),
 array([[0.43521708],
        [0.73300087],
        [0.80093854],
        [0.72375786],
        [0.11383896]]))

In [145]:
R = np.sqrt(np.sum((X - v)**2, axis=0))
np.where(R == np.min(R))

(array([2]),)

In [151]:
X[:, np.where(R == np.min(R))[0]]

array([[0.53],
       [0.53],
       [0.55],
       [0.46],
       [0.56]])

## Бонусная задача:

Я хочу посчитать евклидово расстояние между каждой строкой матрицы A и B

In [152]:
A = np.random.normal(size=(3,4))
B = np.random.normal(size=(3,4))
A, B

(array([[ 0.96104627,  1.55979522,  0.5108663 , -0.22273442],
        [ 0.56419085,  2.53789539,  0.38015827,  0.5435782 ],
        [ 0.63223578, -1.21708491, -1.46533471, -1.20031268]]),
 array([[ 1.8155799 ,  0.26834392, -0.91127547,  0.62337707],
        [-0.19374998, -0.25349218, -1.37838239, -1.28089822],
        [ 1.08930654,  1.19755706, -0.19176903,  0.02038021]]))

In [155]:
np.sqrt(np.sum((A - B)**2, axis=1))

array([2.2663773 , 3.84545164, 3.02513969])

In [161]:
print(A.shape)
A

(3, 4)


array([[ 0.96104627,  1.55979522,  0.5108663 , -0.22273442],
       [ 0.56419085,  2.53789539,  0.38015827,  0.5435782 ],
       [ 0.63223578, -1.21708491, -1.46533471, -1.20031268]])

In [160]:
print(A[None, :, :].shape)
A[None, :, :]

(1, 3, 4)


array([[[ 0.96104627,  1.55979522,  0.5108663 , -0.22273442],
        [ 0.56419085,  2.53789539,  0.38015827,  0.5435782 ],
        [ 0.63223578, -1.21708491, -1.46533471, -1.20031268]]])

In [162]:
print(A[:, None, :].shape)
A[:, None, :]

(3, 1, 4)


array([[[ 0.96104627,  1.55979522,  0.5108663 , -0.22273442]],

       [[ 0.56419085,  2.53789539,  0.38015827,  0.5435782 ]],

       [[ 0.63223578, -1.21708491, -1.46533471, -1.20031268]]])

In [163]:
print(A[:, : ,None].shape)
A[:, :, None]

(3, 4, 1)


array([[[ 0.96104627],
        [ 1.55979522],
        [ 0.5108663 ],
        [-0.22273442]],

       [[ 0.56419085],
        [ 2.53789539],
        [ 0.38015827],
        [ 0.5435782 ]],

       [[ 0.63223578],
        [-1.21708491],
        [-1.46533471],
        [-1.20031268]]])

In [164]:
A[:, None, :]

array([[[ 0.96104627,  1.55979522,  0.5108663 , -0.22273442]],

       [[ 0.56419085,  2.53789539,  0.38015827,  0.5435782 ]],

       [[ 0.63223578, -1.21708491, -1.46533471, -1.20031268]]])

In [165]:
np.array([[ 0.96104627,  1.55979522,  0.5108663 , -0.22273442]]) - B 

array([[-0.85453363,  1.2914513 ,  1.42214177, -0.84611149],
       [ 1.15479625,  1.8132874 ,  1.88924869,  1.0581638 ],
       [-0.12826027,  0.36223816,  0.70263533, -0.24311463]])

In [168]:
np.sqrt(np.sum( (A[:, None, :] - B)**2, axis=2))

array([[2.2663773 , 3.05131722, 0.83693986],
       [2.89672356, 3.84545164, 1.63495881],
       [2.69065569, 1.27468355, 3.02513969]])

In [169]:
np.sqrt(np.sum((A - B)**2, axis=1))

array([2.2663773 , 3.84545164, 3.02513969])