<img src="https://raw.githubusercontent.com/dvgodoy/PyTorch101_ODSC_Europe2020/master/images/linear_dogs.jpg" height="400" width="800"> 


# Андан на экономе

## Семинар 2: numpy

In [8]:
import numpy as np

## Зачем нужен этот пакет? 

`numpy` — библиотека, позволяющая удобно работать с многомерными массивами и матрицами, содержащая математические функции. Кроме того, `numpy` позволяет векторизовать многие вычисления и пригождается в анализе данных.

In [9]:
x = [1, 2, 3]
y = [4, 5, 6]

print(x + y) # списки объединились вмесссте
print(3 * x) # список продублировался трижды 
type(x)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


list

In [10]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y) # в случае numpy поэлементное сложение
print(3 * x) # каждый элемент умножился на число
type(x)

[5 7 9]
[3 6 9]


numpy.ndarray

Работает более быстро.

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x = np.arange(10**5)
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
y = list(x)
y[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
%%timeit 
sum(y)

9.26 ms ± 127 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
%%timeit 
np.sum(x)

70.6 µs ± 561 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


NumPy работает быстро по нескольким причинам:
* Массивы хранятся в непрерывном участке памяти, а все элементы имеют один и тот же тип
* Для вычислений по возможности используются библиотеки линейной алгебры вроде BLAS

# 1. Вектора и матрицы

Посмотрим на основы работы с матрицами и векторами подробнее!

## 1.1 Вектора

Векторно работает не только сложение, но и все другие операции. 

In [21]:
x = np.array([1, -10, 3, 0, 1, 75, 3])
x[3:6]

array([ 0,  1, 75])

In [22]:
x[1:3]

array([-10,   3])

In [23]:
x[3:]

array([ 0,  1, 75,  3])

In [24]:
x[:3]

array([  1, -10,   3])

In [26]:
x[:-3]

array([  1, -10,   3,   0])

In [27]:
x[::-1]

array([  3,  75,   1,   0,   3, -10,   1])

In [29]:
x[1:5:2]

array([-10,   0])

In [32]:
x[::-2]

array([3, 1, 3, 1])

In [34]:
x > 0

array([ True, False,  True, False,  True,  True,  True])

In [35]:
x[x > 0]

array([ 1,  3,  1, 75,  3])

In [ ]:
x[x > 0]

In [38]:
x[(x > 0) | (x % 2 == 0)]

array([  1, -10,   3,   0,   1,  75,   3])

In [39]:
x[(x > 0) | (x <= 70)]

array([  1, -10,   3,   0,   1,  75,   3])

In [44]:
x[[2, 5]]

array([ 3, 75])

In [ ]:
x[[2, 5]]

Есть много сопособов создать в `numpy` вектор. Можно сделать это перечислением элементов, как выше для вектора `x`. А можно с помощью различных специальных функций.

In [ ]:
y = np.arange(start=10, stop=20, step=2) # последнее значение не включается! [10, 20)
y

In [47]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
y = np.ones(5) # вектор длины 5 из единиц
y

array([1., 1., 1., 1., 1.])

In [49]:
y = np.zeros(4) # вектор длины 4 из нулей
y

array([0., 0., 0., 0.])

In [50]:
y = np.random.rand(5)  # случайный вектор, равномерное распределение на [0;1] 
y

array([0.67635594, 0.24161616, 0.96660071, 0.144754  , 0.39969726])

In [54]:
np.ones(x.shape[0])

array([1., 1., 1., 1., 1., 1., 1.])

In [55]:
x

array([  1, -10,   3,   0,   1,  75,   3])

In [56]:
y = np.ones_like(x) # вектор из единиц такой же длины как вектор x
y

array([1, 1, 1, 1, 1, 1, 1])

По сути вектор в `numpy` является одномерным массивом, что соответствует интуитивному определению вектора:

In [57]:
y.shape # размерность вектора

(7,)

In [58]:
np.repeat(5, 3)

array([5, 5, 5])

Более подробно о том, как создавать векторы в `NumPy`, 
см. [документацию](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).

## 1.2 Матрицы

Можно создать матрицу!

In [63]:
A = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
A

array([[1, 2, 3],
       [2, 5, 6],
       [6, 7, 4]])

In [64]:
A.shape # размерность

(3, 3)

In [65]:
A[2]    # вторая строка матрицы

array([6, 7, 4])

In [66]:
A[:,1]  # первый столбец матрицы

array([2, 5, 7])

In [68]:
A[2][1] # можно срезать сначала строку, потом столбец

7

In [69]:
A[2,1]  # либо сразу обе размерности

7

In [70]:
A[1:,1:] # можно найти срез

array([[5, 6],
       [7, 4]])

Более подробно о различных способах индексирования в массивах
см. [документацию](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

Булевы массивы позволяют получать элементы, стоящие на тех же местах что и True в булевом массиве (выражение в квадратных скобках):

In [71]:
A

array([[1, 2, 3],
       [2, 5, 6],
       [6, 7, 4]])

In [74]:
A[A % 2 == 0]

array([2, 2, 6, 6, 4])

In [75]:
is_even = A % 2 == 0 # проверяем четность элементов
print(is_even)

[[False  True False]
 [ True False  True]
 [ True False  True]]


In [76]:
A[is_even]

array([2, 2, 6, 6, 4])

In [77]:
np.where(A % 2 == 0)  # номера строк и столбцов

(array([0, 1, 1, 2, 2]), array([1, 0, 2, 0, 2]))

In [ ]:
idx = np.where(A % 2 == 0)
A[idx]

In [78]:
A[np.where(A % 2 == 0)]

array([2, 2, 6, 6, 4])

Можно создавать специальные матрицы разными функциями, по аналогии с векторами. 

In [79]:
np.ones((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.zeros((3,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.random.normal(size=(3,3))

array([[-0.80713159, -0.1051573 , -0.07704448],
       [-0.19065475, -1.55822904,  0.41641456],
       [ 0.08626473,  0.09968225,  0.7393656 ]])

In [243]:
np.eye(5) # единичная матрица

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [244]:
a = np.eye(5)
np.where(a == 1)

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

Можно изменять размерности, если число элементов позволяет это сделать.

In [83]:
v = np.arange(0, 24, 2)
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [84]:
v.shape

(12,)

In [85]:
v.reshape((3, 4))

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [86]:
v.reshape((3, 6))

ValueError: cannot reshape array of size 12 into shape (3,6)

In [87]:
v.reshape((3, -1)) # -1 => если возможно, найди размерность второй оси автоматически

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [88]:
v.reshape((7, -1))

ValueError: cannot reshape array of size 12 into shape (7,newaxis)

In [89]:
D = np.random.normal(size=(3,3,3))
D.shape

(3, 3, 3)

In [90]:
D  # Вектор из матриц

array([[[-0.51642576,  0.68065012,  0.91993476],
        [ 0.13404056,  1.07947041, -0.81932109],
        [-0.96401089,  0.79984791, -0.15946898]],

       [[ 1.00517717, -0.2820691 , -0.0243887 ],
        [ 0.13808223, -0.06688072, -0.42488259],
        [ 0.02638429, -0.690127  , -1.07966736]],

       [[-0.15847208,  0.58235111,  0.03941555],
        [-0.32950951, -0.7534657 ,  0.07011654],
        [ 0.5380909 ,  0.5110952 ,  1.34307875]]])

Массивы можно объединять:



In [91]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [93]:
A.shape

(2, 2)

In [92]:
np.zeros(A.shape)

array([[0., 0.],
       [0., 0.]])

In [94]:
A = np.array([[1, 2], [3, 4]])
np.hstack((A, np.zeros(A.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.]])

In [95]:
np.vstack((A, np.zeros(A.shape)))

array([[1., 2.],
       [3., 4.],
       [0., 0.],
       [0., 0.]])

In [98]:
np.concatenate((A, np.zeros(A.shape)), axis=1)

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.]])

In [99]:
np.concatenate((A, np.eye(A.shape[1])), axis=0)

array([[1., 2.],
       [3., 4.],
       [1., 0.],
       [0., 1.]])

<img src="https://i.ibb.co/JqsBZBF/matricesconcat.png" style="width: 55vw;"> 

In [100]:
A = np.array([[1, 2, 3], [1, 2, 3]])
B = np.array([[4, 5], [5, 5], [6, 6]])
A, B

(array([[1, 2, 3],
        [1, 2, 3]]),
 array([[4, 5],
        [5, 5],
        [6, 6]]))

In [101]:
np.concatenate((A, B))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [105]:
np.concatenate((A.T, B), axis=1)

array([[1, 1, 4, 5],
       [2, 2, 5, 5],
       [3, 3, 6, 6]])

In [107]:
np.concatenate((A, B.T), axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [5, 5, 6]])

Более подробно о том, как создавать массивы в `numpy`, 
см. [документацию](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).

## 1.3 Векторы, вектор-строки и вектор-столбцы

In [108]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [109]:
b = np.array([[1], [2], [3]])
b

array([[1],
       [2],
       [3]])

In [112]:
np.array([[1, 2, 3], [2], [3, 4]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([1, 2, 3]), list([2]), list([3, 4])], dtype=object)

In [110]:
a.shape

(3,)

In [111]:
b.shape

(3, 1)

__Обратите внимание:__ _вектор_ (одномерный массив) и _вектор-столбец_ или _вектор-строка_ (двумерные массивы) являются различными объектами в `numpy`, хотя математически задают один и тот же объект. В случае одномерного массива кортеж `shape` состоит из одного числа и имеет вид `(n,)`, где `n` — длина вектора. В случае двумерных векторов в `shape` присутствует еще одна размерность, равная единице. 

В большинстве случаев неважно, какое представление использовать, потому что часто срабатывает приведение типов. Но некоторые операции не работают для одномерных массивов. Например, транспонирование:

In [113]:
a

array([1, 2, 3])

In [116]:
a_new = a.T
a_new, a_new.shape

(array([1, 2, 3]), (3,))

In [117]:
b

array([[1],
       [2],
       [3]])

In [119]:
b_new = b.T
b_new, b_new.shape

(array([[1, 2, 3]]), (1, 3))

## 1.4  Умножение матриц и векторов-столбцов

Матрицы можно умножать!

<img src="https://i.ibb.co/xq6tgns/matrixmult.png" style="width: 55vw;"> 

In [127]:
A = np.array([[1, 0], [0, 1]])
B = np.array([[4, 1], [2, 2]])
A, B

(array([[1, 0],
        [0, 1]]),
 array([[4, 1],
        [2, 2]]))

In [128]:
A@B

array([[4, 1],
       [2, 2]])

In [129]:
np.dot(A, B)

array([[4, 1],
       [2, 2]])

In [130]:
A.dot(B)

array([[4, 1],
       [2, 2]])

In [133]:
x = np.array([1, 2])
x

array([1, 2])

In [134]:
B@x

array([6, 6])

__Обратите внимание:__ операция __`*`__ производит над матрицами покоординатное умножение, а не матричное!

<img src="https://i.ibb.co/CtC2RqY/elementwisemult.png" style="width: 55vw;"> 

In [135]:
A * B

array([[4, 0],
       [0, 2]])

Базовые арифметические операции над массивами выполняются поэлементно.

In [136]:
A + B

array([[5, 1],
       [2, 3]])

In [137]:
A * 1.0 / B

array([[0.25, 0.  ],
       [0.  , 0.5 ]])

In [138]:
A + 1 

array([[2, 1],
       [1, 2]])

In [139]:
3 * A

array([[3, 0],
       [0, 3]])

In [140]:
A ** 2

array([[1, 0],
       [0, 1]])

Поскольку операции выполняются поэлементно, операнды бинарных операций должны иметь одинаковый размер. Тем не менее, операция может быть корректно выполнена, если размеры операндов таковы, что они могут быть расширены до одинаковых размеров. Данная возможность называется [broadcasting](http://www.scipy-lectures.org/intro/numpy/operations.html#broadcasting):
![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [142]:
vec = np.arange(0, 40, 10)
vec

array([ 0, 10, 20, 30])

In [147]:
np.tile(vec, (3, 1)).T

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [148]:
A = np.tile(np.arange(0, 40, 10), (3, 1)).T 
A

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [149]:
A + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

## 1.5 Другие операции над матрицами

In [150]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
A  

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [153]:
A.T  # Транспонирование

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [154]:
np.linalg.det(A) # Определитель

-2.9999999999999982

In [155]:
np.linalg.matrix_rank(A) # Ранг матрицы

3

In [156]:
np.diag(A) # главная диагональ

array([ 1,  5, 10])

In [157]:
B = np.linalg.inv(A) # обратная матрица
B

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [158]:
A@B # Единичная матрица

array([[1.0000000e+00, 8.8817842e-16, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 8.8817842e-16],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00]])

In [159]:
np.sum((A@B - np.eye(3))**2) # невязка между элементами

1.4199496293978212e-29

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям. Если речь о матрицах, то по строкам или столбцам:

In [160]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [161]:
A.sum()

46

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам.

In [162]:
np.sum(A, axis=1)

array([ 6, 15, 25])

In [163]:
np.sum(A, axis=0)

array([12, 15, 19])

In [164]:
A.sum(axis=0) # то же самое, но как метод

array([12, 15, 19])

# 2. Решаем задачи

В будущем вы будете учить анализ данных. Там неожиданно выяснится, что любые данные - это матрица. Там-то вы и увидите впервые всю мощь numpy. 

### Задачка 1 (максимум перед нулем) 
 
Реализуйте функцию, возвращающую максимальный элемент в векторе $x$ среди элементов, перед которыми стоит нулевой. 

Например, для `x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])` ответом является `5`. Если нулевых элементов нет, функция должна возвращать `None`.

In [192]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [179]:
x == 0

array([False, False, False, False, False])

In [194]:
shifted_x = np.hstack((1, x))
shifted_x

array([1, 6, 2, 0, 3, 0, 0, 5, 7, 0])

In [195]:
mask = (shifted_x == 0)
mask_new = mask[:-1]
mask_new

array([False, False, False,  True, False,  True,  True, False, False])

In [196]:
elements = x[mask_new]
elements

array([3, 0, 5])

In [184]:
elements.shape[0]

0

In [186]:
np.size(elements) == 0

True

In [197]:
np.max(elements)

5

In [205]:
def post_zero_max(x):
    shifted_x = np.hstack((1, x))
    mask = (shifted_x == 0)
    mask_new = mask[:-1]
    elements = x[mask_new]
    if np.size(elements) == 0:
        return None
    else:
        return np.max(elements)

In [206]:
print(x)
print(post_zero_max(x))

[6 2 0 3 0 0 5 7 0]
5


In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ▬▬ι═══════  Peace is a lie, there is only passion.

In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ▬▬ι═══════   Through passion, I gain strength.

__Зачем?__ 

К вам в голову тут должна была прийти мысль: "Зачем? Можно же использовать цикл!". Да, можно. Но векторные вычисления работают на порядок быстрее. Часто сделать их намного удобнее, чем написать цикл.

### Задачка 2 (нормировка) 


Есть матрица $X$. Нужно отнормировать её столбцы к отрезку $[0;1]:$

$$
x^{*} = \frac{x−min(x)}{max(x)−min(x)}
$$

In [210]:
X = np.random.normal(loc=10, scale=1, size=(5, 5))
X

array([[ 8.74036244,  8.19052901,  9.94357344,  9.82961395, 11.24351258],
       [ 9.36938686,  9.07269939, 10.49973496, 10.78897262, 10.49283749],
       [ 8.85963337, 10.76015928,  9.51036292, 10.99663123,  7.72691665],
       [ 7.41096981, 10.13504171, 10.16301422,  8.86390365, 11.08979256],
       [10.20979727, 11.09347152,  9.88223054, 10.00521292,  9.62258614]])

In [213]:
X.min(axis=0)

array([7.41096981, 8.19052901, 9.51036292, 8.86390365, 7.72691665])

In [215]:
(X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

array([[0.47498199, 0.        , 0.43786412, 0.45280528, 1.        ],
       [0.69972768, 0.30388834, 1.        , 0.90263238, 0.7865336 ],
       [0.51759659, 0.88518125, 0.        , 1.        , 0.        ],
       [0.        , 0.66984196, 0.65966216, 0.        , 0.95628727],
       [1.        , 1.        , 0.37586227, 0.53514067, 0.53906378]])

In [217]:
(X - X.min()) / (X.max() - X.min())

array([[0.34686961, 0.20340522, 0.66081549, 0.6310808 , 1.        ],
       [0.51099679, 0.43358409, 0.80593103, 0.8813999 , 0.80413132],
       [0.37799019, 0.87388182, 0.54778074, 0.93558289, 0.08243792],
       [0.        , 0.71077404, 0.71807272, 0.3791044 , 0.95989085],
       [0.73027951, 0.96085078, 0.64480969, 0.67689867, 0.5770624 ]])

In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ▬▬ι═══════   Through strength, I gain power.

In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ▬▬ι═══════   Through power, I gain victory.

__Зачем?__ 

К вам в голову тут должна была прийти мысль: "Зачем вообще делать это?". 

Обычно в машинном обучении по строчкам записывают наблюдения, по столбцам разные признаки. Часто между объектами надо считать расстояния. Представим, что у нас в выборке два наблюдения. Петя, который весит $50$ кг при росте $1$ метр. И Вася, который вести $75$ кг при росте в $1.5$ метра. То есть Петя описывается вектором $(50, 1)$, а Вася $(75, 1.5)$. 

Если нам надо вычислить между парнями расстояние, мы будем делать это так:

In [ ]:
print((50 - 75) ** 2)
print((1 - 1.5) ** 2)
(50 - 75) ** 2 + (1 - 1.5) ** 2

Намного больше внимания уделяется весу. Чтобы такого не возникало, надо отнормировать все признаки к одной шкале. Например, отрезку $[0;1]$. 

> Если хотите узнать о том как линал используется в машинном обучении больше, смотрите небольшой видос про рекомендательные системы ["От матрицы до больших данных"](https://www.youtube.com/watch?v=Or119IXozCM)

### Задачка 3 (ближайший в матрице) 

Реализуйте функцию, принимающую на вход матрицу $X$ и некоторое число $a$ и возвращающую ближайший к числу элемент матрицы. А потом перепишите её так, чтобы она возвращала самый дальний элемент. 

In [250]:
X = np.arange(24).reshape(6, 4)
a = 3.5
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [251]:
X - a

array([[-3.5, -2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5,  3.5],
       [ 4.5,  5.5,  6.5,  7.5],
       [ 8.5,  9.5, 10.5, 11.5],
       [12.5, 13.5, 14.5, 15.5],
       [16.5, 17.5, 18.5, 19.5]])

In [252]:
diff = np.abs(X - a)
diff

array([[ 3.5,  2.5,  1.5,  0.5],
       [ 0.5,  1.5,  2.5,  3.5],
       [ 4.5,  5.5,  6.5,  7.5],
       [ 8.5,  9.5, 10.5, 11.5],
       [12.5, 13.5, 14.5, 15.5],
       [16.5, 17.5, 18.5, 19.5]])

In [253]:
min_element = np.min(diff)
min_element

0.5

In [254]:
ind = np.where(diff == min_element)
ind

(array([0, 1]), array([3, 0]))

In [242]:
ind[0]

2

In [234]:
ind[0][0], ind[1][0]

(2, 1)

In [256]:
X[ind][0]

3

In [236]:
X[ind[0][0], ind[1][0]]

9

In [257]:
def closest_element(X, a):
    diff = np.abs(X - a)
    min_element = np.min(diff)
    ind = np.where(diff == min_element)
    return X[ind]

In [258]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [259]:
closest_element(X, 3.5)

array([3, 4])

In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ▬▬ι═══════  Through victory, my chains are broken.

In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ▬▬ι═══════  The Force shall free me.

### Задачка 4 (ближайшая строка в матрице) 

Усложним предыдущую задачу! Дана матрица $X$ и вектор $v$. Нужно найти в матрице $X$ строку, которая будет ближе всего к вектору $v$. 

$$
 \rho_{2}\left( x, y \right) = \left\Vert x - y \right\Vert_{2} = 
 \sqrt{\sum_{i=1}^n \left( x_{i} - y_{i} \right)^2}.
$$

In [260]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [268]:
v = np.arange(4)
v

array([0, 1, 2, 3])

In [272]:
diff = (X - v)**2
diff

array([[  0,   0,   0,   0],
       [ 16,  16,  16,  16],
       [ 64,  64,  64,  64],
       [144, 144, 144, 144],
       [256, 256, 256, 256],
       [400, 400, 400, 400]])

In [277]:
dist = np.sqrt(diff.sum(axis=1))
dist

array([ 0.,  8., 16., 24., 32., 40.])

In [287]:
X[np.where(dist == np.min(dist))]

array([[0, 1, 2, 3]])

In [284]:
X[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [288]:
def closest_vec(X, v):
    diff = (X - v)**2
    dist = np.sqrt(diff.sum(axis=1))
    return X[np.where(dist == np.min(dist))]

In [289]:
closest_vec(X, v)

array([[0, 1, 2, 3]])

In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ▬▬ι═══════  bzzzzzzzzzz

__Зачем?__ 

Зачем вообще кому-то нужны задания 3 и 4?! В машинном обучения всюду вектора! Например, есть волшебная технология __word2vec__. В ней все слова превращают в вектора так, чтобы в них был закодирован смысл слова. В итоге неожиданно оказывается, что эти вектора можно складывать и вычитать. Если взять вектор _король_, вычесть из него _мужчина_ и добавить _женщина_, внезапно получится вектор, самым близким к которому является _королева_. 

Все эти вычисления удобно делать в `numpy`, написанными нами функциями. Поиграться с такой моделью и калькулятором слов можно [на сайте resvectores](https://rusvectores.org/ru/calculator/#)

### Больше заданий для практики можно найти: 

- В [необязательном контесте](https://official.contest.yandex.ru/contest/25960/enter/) вас ждут простые и не очень задачи на numpy
- В сборнике [100 упражнений на `numpy`](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md), там же [вариант без решения с подсказками.](https://github.com/rougier/numpy-100) Некоторые упражнения странные и бесполезные. 

Ещё можно почитать [numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/)

------------------------

# 3. Бонус-трек: линейная алгебра

> Эту часть тетрадки мы __НЕ будем__ делать на семинаре. Её можно помотреть после него. Внутри много полезного функционала. Но ясное дело далеко не весь. Если хочется больше линала, да ещё и с python, добро пожаловать [курс по линал от ББ Демешева](https://www.coursera.org/learn/lineinaya-algebra) 

В этой части тетрадки мы поглубже поссмотим на функционал пакета. Далее нам понабится модуль `numpy.linalg`, реализующий некоторые приложения линейной алгебры.

## 3.1 Нормы векторов 

Вспомним некоторые нормы, которые можно ввести в пространстве $\mathbb{R}^{n}$, и рассмотрим, с помощью каких библиотек и функций их можно вычислять в `numpy`.  Для вычисления различных норм мы используем функцию `numpy.linalg.norm(x, ord=None, ...)`, где `x` — исходный вектор, `ord` — параметр, определяющий норму (мы рассмотрим два варианта его значений — 1 и 2). 

### $\ell_{2}$ норма

$\ell_{2}$ норма (также известная как евклидова норма)
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{2} = \sqrt{\sum_{i=1}^n \left( x_{i} \right)^2}.
$$

Ей в функции `numpy.linalg.norm(x, ord=None, ...)` соответствует параметр `ord=2`.

In [ ]:
from numpy.linalg import norm

In [ ]:
a = np.array([1, 2, -3])
norm(a, ord=2)

### $\ell_{1}$ норма

$\ell_{1}$ норма 
(также известная как [манхэттенское расстояние](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%81%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B8%D1%85_%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B0%D0%BB%D0%BE%D0%B2))
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

Ей в функции `numpy.linalg.norm(x, ord=None, ...)` соответствует параметр `ord=1`.

In [ ]:
a = np.array([1, 2, -3])
norm(a, ord=1)

Более подробно о том, какие еще нормы (в том числе матричные) можно вычислить, см. [документацию](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linalg.norm.html). 

## 3.2   Расстояния между векторами

Для двух векторов $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ и $y = (y_{1}, \dots, y_{n}) \in \mathbb{R}^{n}$ $\ell_{1}$ и $\ell_{2}$ раccтояния вычисляются по следующим формулам соответственно:

$$
 \rho_{1}\left( x, y \right) = \left\Vert x - y \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} - y_{i} \right|
$$

$$
 \rho_{2}\left( x, y \right) = \left\Vert x - y \right\Vert_{2} = 
 \sqrt{\sum_{i=1}^n \left( x_{i} - y_{i} \right)^2}.
$$

In [ ]:
a = np.array([1, 2, -3])
b = np.array([-4, 3, 8])

In [ ]:
norm(a - b, ord=1)

In [ ]:
norm(a - b, ord=2)

Также расстояние между векторами можно посчитать с помощью функции  `scipy.spatial.distance.cdist(XA, XB, metric='euclidean', p=2, ...)` из модуля `scipy`, предназначенного для выполнения научных и инженерных расчётов. 

In [ ]:
from scipy.spatial.distance import cdist

`scipy.spatial.distance.cdist(...)` требует, чтобы размерность `XA` и `XB` была как минимум двумерная. По этой причине для использования этой функции необходимо преобразовать _векторы_, которые мы рассматриваем в этом ноутбуке, к _вектор-строкам_ с помощью способов, которые мы рассмотрим ниже. 

Параметры `XA, XB` — исходные вектор-строки, а `metric` и `p` задают метрику расстояния
(более подробно о том, какие метрики можно использовать, см. [документацию](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.spatial.distance.cdist.html)).

Первый способ из _вектора_ сделать _веткор-строку (вектор-столбец)_ — это использовать _метод_ `array.reshape(shape)`, где параметр `shape` задает размерность вектора (кортеж чисел).

In [ ]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

print('Вектор a:', a)
print('Его размерность:', a.shape)
print('Вектор b:', b)
print('Его размерность:', b.shape)

In [ ]:
a = a.reshape((1, 3))
b = b.reshape((1, 3))

print('После применения метода reshape:\n')
print('Вектор-строка a:', a)
print('Его размерность:', a.shape)
print('Вектор-строка b:', b)
print('Его размерность:', b.shape)

In [ ]:
print('Манхэттенское расстояние между a и b (через cdist):', cdist(a, b, metric='cityblock'))

Заметим, что после применения этого метода размерность полученных вектор-строк будет равна `shape`. Следующий метод позволяет сделать такое же преобразование, но не изменяет размерность исходного вектора.  

В `numpy` к размерностям объектов можно добавлять фиктивные оси с помощью `np.newaxis`. Для того, чтобы понять, как это сделать, рассмотрим пример:

In [ ]:
d = np.array([3, 0, 8, 9, -10])

print('Вектор d:', d)
print('Его размерность:', d.shape)

In [ ]:
print('Вектор d с newaxis --> вектор-строка:\n', d[np.newaxis, :])
print('Полученная размерность:', d[np.newaxis, :].shape)
print(' ')
print('Вектор d с newaxis --> вектор-столбец:\n', d[:, np.newaxis])
print('Полученная размерность:', d[:, np.newaxis].shape)

Важно, что `np.newaxis` добавляет к размерности ось, длина которой равна 1 (это и логично, так как количество элементов должно сохраняться). Таким образом, надо вставлять новую ось там, где нужна единица в размерности. 

Теперь посчитаем расстояния с помощью `scipy.spatial.distance.cdist(...)`, используя `np.newaxis` для преобразования векторов:

In [ ]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

print('Евклидово расстояние между a и b (через cdist):', cdist(a[np.newaxis, :], 
                                                               b[np.newaxis, :], 
                                                               metric='euclidean'))

Эта функция также позволяет вычислять попарные расстояния между множествами векторов. Например, пусть у нас имеется матрица размера $m_{A} \times n$. Мы можем рассматривать ее как описание некоторых $m_{A}$ наблюдений в $n$-мерном пространстве. Пусть также имеется еще одна аналогичная матрица размера $m_{B} \times n$, где  $m_{B}$ векторов в том же $n$-мерном пространстве. Часто необходимо посчитать попарные расстояния между векторами первого и второго множеств. 

В этом случае можно пользоваться функцией `scipy.spatial.distance.cdist(XA, XB, metric='euclidean', p=2, ...)`, где в качестве `XA, XB` необходимо передать две описанные матрицы. Функция возаращает матрицу попарных расстояний размера $m_{A} \times m_{B}$, где элемент матрицы на $[i, j]$-ой позиции равен расстоянию между $i$-тым вектором первого множества и $j$-ым вектором второго множества. 

В данном случае эта функция предподчительнее `numpy.linalg.norm(...)`, так как она вычисляет попарные расстояния быстрее и эффективнее. 

## 3.3 Скалярное произведение и угол между векторами

In [ ]:
a = np.array([0, 5, -1])
b = np.array([-4, 9, 3])

Скалярное произведение в пространстве $\mathbb{R}^{n}$ для двух векторов $x = (x_{1}, \dots, x_{n})$ и $y = (y_{1}, \dots, y_{n})$ определяется как:

$$
\langle x, y \rangle = \sum_{i=1}^n x_{i} y_{i}.
$$

Скалярное произведение двух векторов можно вычислять помощью функции `numpy.dot(a, b, ...)` или _метода_ `vec1.dot(vec2)`, где `vec1` и `vec2` — исходные векторы. Также эти функции подходят для матричного умножения, о котором речь пойдет в следующем уроке. 

In [ ]:
np.dot(a, b) # через функцию

In [ ]:
a.dot(b) # через метод

In [ ]:
a@b # через матричное умножение

Длиной вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ называется квадратный корень из скалярного произведения, то есть длина равна евклидовой норме вектора:

$$
\left| x \right| = \sqrt{\langle x, x \rangle} = \sqrt{\sum_{i=1}^n x_{i}^2} =  \left\Vert x \right\Vert_{2}.
$$

Теперь, когда мы знаем расстояние между двумя ненулевыми векторами и их длины, мы можем вычислить угол между ними через скалярное произведение:

$$
\langle x, y \rangle = \left| x \right| | y | \cos(\alpha)
\implies \cos(\alpha) = \frac{\langle x, y \rangle}{\left| x \right| | y |},
$$

где $\alpha \in [0, \pi]$ — угол между векторами $x$ и $y$.

In [ ]:
cos_angle = np.dot(a, b) / norm(a) / norm(b)
cos_angle  # косинус угла

In [ ]:
np.arccos(cos_angle) # сам угол

Более подробно о том, как вычислять скалярное произведение в `numpy`, 
см. [документацию](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html#matrix-and-vector-products).

## 3.4 Системы линейных уравнений

__Системой линейных алгебраических уравнений__ называется система вида $Ax = b$, где $A \in \mathbb{R}^{n \times m}, x \in \mathbb{R}^{m \times 1}, b \in \mathbb{R}^{n \times 1}$. В случае квадратной невырожденной матрицы $A$ решение системы единственно.

В `numpy` решение такой системы можно найти с помощью функции `numpy.linalg.solve(a, b)`, где первый аргумент — матрица $A$, второй — столбец $b$.

In [ ]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

Убедимся, что вектор $x$ действительно является решением системы:

In [ ]:
A.dot(x)

Бывают случаи, когда решение системы не существует. Но хотелось бы все равно "решить" такую систему. Логичным кажется искать такой вектор $x$, который минимизирует выражение $\left\Vert Ax - b\right\Vert^{2}$ — так мы приблизим выражение $Ax$ к $b$.

В `numpy` такое псевдорешение можно искать с помощью функции `numpy.linalg.lstsq(a, b, ...)`, где первые два аргумента такие же, как и для функции `numpy.linalg.solve()`. 

Помимо решения функция возвращает еще три значения, которые нам сейчас не понадобятся.

In [ ]:
A = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])
x, res, r, s = np.linalg.lstsq(A, b)

In [ ]:
A

In [ ]:
b

In [ ]:
x

## 3.5 Собственные числа и собственные вектора матрицы

Для квадратных матриц определены понятия __собственного вектора__ и __собственного числа__.

Пусть $A$ — квадратная матрица и $A \in \mathbb{R}^{n \times n}$. __Собственным вектором__ матрицы $A$ называется такой ненулевой вектор $x \in \mathbb{R}^{n}$, что для некоторого $\lambda \in \mathbb{R}$ выполняется равенство $Ax = \lambda x$. При этом $\lambda$ называется __собственным числом__ матрицы $A$. Собственные числа и собственные векторы матрицы играют важную роль в теории линейной алгебры и ее практических приложениях.

В `numpy` собственные числа и собственные векторы матрицы вычисляются с помощью функции `numpy.linalg.eig(a)`, где `a` — исходная матрица. В качестве результата эта функция выдает одномерный массив `v` собственных чисел и двумерный массив `w`, в котором по столбцам записаны собственные вектора, так что вектор `w[:, i]` соотвествует собственному числу `v[i]`.

In [ ]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [ ]:
w

In [ ]:
v

__Обратите внимание:__ у вещественной матрицы собственные значения или собственные векторы могут быть комплексными.

## 3.6  Комплексные числа в питоне

__Комплексными числами__ называются числа вида $x + iy$, где $x$ и $y$ — вещественные числа, а $i$ — мнимая единица (величина, для которой выполняется равенство $i^{2} = -1$). Множество всех комплексных чисел обозначается буквой $\mathbb{C}$ (подробнее про комплексные числа см. [википедию](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81%D0%BD%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE)).

В питоне комплескные числа можно задать следующим образом ( $j$ обозначает мнимую единицу):

In [ ]:
a = 3 + 2j
a

In [ ]:
b = 1j
b

In [ ]:
a * a

In [ ]:
a / (4 - 5j)

In [ ]:
np.abs(a)

In [ ]:
np.sqrt(3**2 + 2**2)