In [2]:
import numpy as np

In [20]:
n = 3

A = np.random.rand(n, n)
A = A.T @ A 
A

array([[0.53184104, 0.2551012 , 0.24133842],
       [0.2551012 , 0.47865814, 0.69497415],
       [0.24133842, 0.69497415, 1.08122463]])

In [21]:
lam, Q = np.linalg.eig(A)
Q@np.diag(lam)@Q.T

array([[0.53184104, 0.2551012 , 0.24133842],
       [0.2551012 , 0.47865814, 0.69497415],
       [0.24133842, 0.69497415, 1.08122463]])

In [22]:
np.trace(Q@np.diag(lam)@Q.T)

2.0917238132940317

In [23]:
np.linalg.norm(Q.T@Q - np.eye(3))

5.67464084063076e-16

In [26]:
2*Q@np.diag(lam)

array([[ 0.96909836,  0.82797557,  0.00279698],
       [ 1.7630876 , -0.00791575, -0.01329179],
       [ 2.59787395, -0.30349186,  0.00797731]])

In [14]:
Q@np.diag(lam)

array([[-0.99387445, -0.01395009, -0.06360235],
       [-2.61607403,  0.0086472 , -0.06446478],
       [-2.4811462 , -0.00352945,  0.09344769]])

In [1]:
import numpy as np

In [2]:
x = np.array([[1], [2], [3]])
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A@x

array([[14],
       [32],
       [50]])

In [12]:
A[:,None, :] @ x

array([[[14]],

       [[32]],

       [[50]]])

In [9]:
a = set(RIDER_YANGO_TAGS.values())| set(DRIVER_YANGO_TAGS.values())| set(RIDER_GO_TAGS.values()) | set(DRIVER_GO_TAGS.values())

In [10]:
a

{'Inappropriate_conversations',
 'Missing_person',
 'Other',
 'PR_critical_case',
 'Physical_assault_reports',
 'Police_involvement',
 'Reckless driving reports',
 'Reckless_driving_reports',
 'Road accident reports',
 'Road_accident_reports',
 'Sexual assault reports',
 'Sexual_assault_reports',
 'Sexual_misconduct_reports',
 'Theft',
 'Threat',
 'Unintentional_health_damage',
 'Verbal_altercation_reports'}

In [12]:
a - {
    "Missing_person", "Theft", "Verbal_altercation_reports", "Threat", "Police_involvement",
    "Physical_assault_reports", "PR_critical_case", "Unintentional_health_damage", "Other",
    "Sexual_misconduct_reports", "Road_accident_reports", "Inappropriate_conversations", 
    "Reckless_driving_reports", "Sexual_assault_reports"}

{'Reckless driving reports', 'Road accident reports', 'Sexual assault reports'}

In [2]:
RIDER_YANGO_TAGS = {
    'rd_irt_missing_driver': 'Missing_person',
    'rd_irt_missing_person': 'Missing_person',
    'rd_irt_missing_rider': 'Missing_person',
    'rd_irt_major_altercation_jumped_out_of_the_car': 'Other',
    'rd_irt_online_sos': 'Other',
    'rd_irt_online_sos_failed_contact': 'Other',
    'rd_irt_online_not_an_urgent_request': 'Other',
    'rd_irt_online_without_order': 'Other',
    'rd_irt_online_random': 'Other',
    'rd_irt_online': 'Other',
    'rd_irt_fraud': 'Other',
    'rd_irt_temporary_response': 'Other',
    'closed_by_merge': 'Other',
    'rd_irt_physical_altercation_damage': 'Other',
    'rd_irt_legal_issue_managers': 'Other',
    'rd_irt_extra_passanger_car': 'Other',
    'rd_irt_not_urgent_request': 'Other',
    'rd_irt_forgotten_medicine': 'Other',
    'rd_irt_detailed_specify': 'Other',
    'rd_irt_accident_compensation': 'Other',
    'rd_irt_damaged_item': 'Other',
    'rd_irt_forgotten_weapons': 'Other',
    'rd_irt': 'Other',
    'rd_irt_legal_issue': 'Other',
    'rd_irt_request': 'Other',
    'rd_irt_physical_altercation': 'Physical_assault_reports',
    'rd_irt_physical_altercation_third_parties': 'Physical_assault_reports',
    'rd_irt_physical_altercation_physical_assault': 'Physical_assault_reports',
    'rd_irt_verbal_altercation_kidnapping': 'Physical_assault_reports',
    'rd_irt_verbal_altercation_holding_in_the_car': 'Physical_assault_reports',
    'rd_irt_verbal_altercation_hold_for_payment': 'Physical_assault_reports',
    'rd_irt_major_altercation_police_involvement': 'Police_involvement',
    'rd_irt_urgent_traffic_stop': 'Police_involvement',
    'rd_irt_request_from_police': 'Police_involvement',
    'rd_irt_threat_terrorism_user': 'PR_critical_case',
    'rd_irt_threat_terrorism_driver': 'PR_critical_case',
    'rd_irt_sexual_misconduct_rape': 'PR_critical_case',
    'rd_irt_fatality': 'PR_critical_case',
    'rd_irt_verbal_altercation_blogger_driver': 'PR_critical_case',
    'rd_irt_threat_terrorism': 'PR_critical_case',
    'rd_irt_grave_traffic_violation_sleepy_driver': 'Reckless_driving_reports',
    'rd_irt_dangerous_driving_falling_asleep': 'Reckless_driving_reports',
    'rd_irt_dangerous_driving': 'Reckless_driving_reports',
    'rd_irt_dangerous_driving_drug_alcohol': 'Reckless_driving_reports',
    'rd_irt_dangerous_driving_affected_animal': 'Road_accident_reports',
    'rd_irt_dangerous_driving_affected_animal_without_trip': 'Road_accident_reports',
    'rd_irt_accident_without_trip': 'Road_accident_reports',
    'rd_irt_accident_before_boarding': 'Road_accident_reports',
    'rd_irt_accident': 'Road_accident_reports',
    'rd_irt_sexual_misconduct_sexual_assault': 'Sexual_assault_reports',
    'rd_irt_sexual_misconduct_inappropriate_behavior': 'Sexual_assault_reports',
    'rd_irt_sexual_misconduct_calls_and_messages_after_trip': 'Sexual_misconduct_reports',
    'rd_irt_major_altercation_inappropriate_conversations': 'Sexual_misconduct_reports',
    'rd_irt_sexual_misconduct_indecent_exposure': 'Sexual_misconduct_reports',
    'rd_irt_sexual_misconduct_inappropriate_comments': 'Sexual_misconduct_reports',
    'rd_irt_sexual_misconduct': 'Sexual_misconduct_reports',
    'rd_irt_heist': 'Theft',
    'rd_irt_theft': 'Theft',
    'rd_irt_major_altercation_left_in_a_dangerous_place': 'Threat',
    'rd_irt_threat_suicide_user': 'Threat',
    'rd_irt_threat_suicide_driver': 'Threat',
    'rd_irt_threat_suicide': 'Threat',
    'rd_irt_threat_arrive_office_user': 'Threat',
    'rd_irt_threat_arrive_office_driver': 'Threat',
    'rd_irt_threat_arrive_office': 'Threat',
    'rd_irt_verbal_altercation_threatended_weapons': 'Threat',
    'rd_irt_physical_altercation_used_weapons': 'Threat',
    'rd_irt_verbal_altercation_weapons_in_car': 'Threat',
    'rd_irt_verbal_altercation_threat_intimidation': 'Threat',
    'rd_irt_inappropriate_contact_after_trip_calls_or_messages': 'Threat',
    'rd_irt_verbal_altercation_leaving_in_danger': 'Threat',
    'rd_irt_verbal_altercation_stalking': 'Threat',
    'rd_irt_health_soft': 'Unintentional_health_damage',
    'rd_irt_health_client': 'Unintentional_health_damage',
    'rd_irt_health_driver': 'Unintentional_health_damage',
    'rd_irt_health': 'Unintentional_health_damage',
    'rd_irt_mental_health': 'Unintentional_health_damage',
    'rd_irt_verbal_altercation_without_trip_third_parties_without_physical_altercation': 'Verbal_altercation_reports',
    'rd_irt_verbal_altercation_without_trip_third_parties': 'Verbal_altercation_reports',
    'rd_irt_verbal_altercation_third_parties_without_physical_altercation': 'Verbal_altercation_reports',
    'rd_irt_verbal_altercation_with_taxi_company': 'Verbal_altercation_reports',
    'rd_irt_verbal_altercation_without_trip': 'Verbal_altercation_reports',
    'rd_irt_discriminatory_comments': 'Verbal_altercation_reports',
    'rd_irt_verbal_altercation': 'Verbal_altercation_reports',
    'rd_irt_discrimination': 'Verbal_altercation_reports',
    'rd_irt_service_denial': 'Verbal_altercation_reports',
    'rd_irt_verbal_altercation_major': 'Verbal_altercation_reports'
};

DRIVER_YANGO_TAGS = {
    'dr_complaint_irt_missing_passenger': 'Missing_person',
    'dr_complaint_irt_missing_driver': 'Missing_person',
    'dr_complaint_irt_from_driver': 'Other',
    'dr_complaint_irt_duplicate_request': 'Other',
    'dr_complaint_irt_need_more_details': 'Other',
    'dr_complaint_irt_fraud': 'Other',
    'dr_complaint_irt_not_urgent_request': 'Other',
    'dr_irt_accident_compensation': 'Other',
    'dr_complaint_irt_drugs_life_saving_medication_left_in_the_car': 'Other',
    'dr_complaint_irt_drugs_transfer_through_the_driver': 'Other',
    'dr_complaint_irt_drugs_left_in_the_car': 'Other',
    'dr_complaint_irt_altercation': 'Other',
    'dr_complaint_irt_forgotten_weapons': 'Other',
    'dr_complaint_irt': 'Other',
    'dr_complaint_irt_physical_altercation_physical_assault': 'Physical_assault_reports',
    'dr_complaint_irt_major_altercation_holding_hostage': 'Physical_assault_reports',
    'dr_complaint_irt_major_altercation_robbery': 'Physical_assault_reports',
    'dr_complaint_irt_sexual_misconduct_sexual_assault': 'Physical_assault_reports',
    'dr_complaint_irt_sexual_misconduct_inappropriate_behavior': 'Physical_assault_reports',
    'irt_request_from_police_africa': 'Police_involvement',
    'irt_request_from_police': 'Police_involvement',
    'dr_complaint_irt_rider_detained_police': 'Police_involvement',
    'dr_complaint_irt_driver_detained_police': 'Police_involvement',
    'dr_complaint_irt_threats_terrorist_attack': 'PR_critical_case',
    'dr_complaint_irt_fatality': 'PR_critical_case',
    'dr_complaint_irt_sexual_misconduct_rape': 'PR_critical_case',
    'dr_irt_accident_without_order': 'Road accident reports',
    'dr_irt_accident': 'Road accident reports',
    'dr_complaint_irt_sexual_misconduct_inappropriate_comments': 'Sexual_misconduct_reports',
    'dr_complaint_irt_sexual_misconduct_indecent_exposure': 'Sexual_misconduct_reports',
    'dr_complaint_irt_sexual_misconduct': 'Sexual_misconduct_reports',
    'dr_complaint_irt_theft': 'Theft',
    'dr_complaint_irt_threats_arrive_office': 'Threat',
    'dr_complaint_irt_threats': 'Threat',
    'dr_complaint_irt_passenger_made_emergency': 'Threat',
    'dr_complaint_irt_verbal_altercation_threat_intimidation': 'Threat',
    'dr_complaint_irt_verbal_altercation_stalking': 'Threat',
    'dr_complaint_irt_physical_altercation_damage': 'Threat',
    'dr_complaint_irt_verbal_altercation_weapons_in_car': 'Threat',
    'dr_complaint_irt_verbal_altercation_threatended_weapons': 'Threat',
    'dr_complaint_irt_physical_altercation_used_weapons': 'Threat',
    'dr_complaint_irt_inappropriate_contact_after_trip_calls_or_messages': 'Threat',
    'irt_health_client': 'Unintentional_health_damage',
    'irt_health_driver': 'Unintentional_health_damage',
    'irt_health': 'Unintentional_health_damage',
    'dr_complaint_irt_verbal_altercation_major': 'Verbal_altercation_reports',
    'dr_complaint_irt_altercation_conflict_without_order': 'Verbal_altercation_reports',
    'dr_complaint_irt_discriminatory_comments': 'Verbal_altercation_reports'
};

RIDER_GO_TAGS = {
    'rd_irt_sexual_misconduct_attempted_rape': 'PR_critical_case',
    'rd_irt_sexual_misconduct_indecent_exposure_selfsatisfaction': 'Sexual assault reports',
    'rd_irt_sexual_misconduct_indecent_exposure_natural_need': 'Other',
    'rd_irt_sexual_misconduct_fraud': 'Other',
    'rd_irt_sexual_misconduct_without_trip': 'Sexual_misconduct_reports',
    'rd_irt_sexual_misconduct_act_of_rape': 'PR_critical_case',
    'rd_irt_discriminatory_comments': 'Verbal_altercation_reports',
    'rd_irt_service_denial': 'Verbal_altercation_reports',
    'rd_irt_dangerous_driving': 'Reckless driving reports',
    'rd_irt_dangerous_driving_falling_asleep': 'Reckless driving reports',
    'rd_irt_sexual_misconduct_inappropriate_comments': 'Sexual_misconduct_reports',
    'rd_irt_sexual_misconduct_inappropriate_behavior': 'Sexual assault reports',
    'rd_irt_sexual_misconduct_sexual_assault': 'Sexual assault reports',
    'rd_irt_verbal_altercation': 'Verbal_altercation_reports',
    'rd_irt_verbal_altercation_threat_intimidation': 'Threat',
    'rd_irt_inappropriate_contact_after_trip_calls_or_messages': 'Threat',
    'rd_irt_verbal_altercation_stalking': 'Threat',
    'rd_irt_verbal_altercation_holding_in_the_car': 'Physical_assault_reports',
    'rd_irt_verbal_altercation_without_trip': 'Verbal_altercation_reports',
    'rd_irt_accident_insurance': 'Other',
    'rd_irt_request_from_police': 'Police_involvement',
    'rd_irt_legal_issue_refuse': 'Other',
    'rd_irt_legal_issue_satisfied_partially': 'Other',
    'rd_irt_legal_issue_managers': 'Other',
    'rd_irt_legal_issue_managers_no_answer': 'Other',
    'rd_irt_legal_issue_managers_satisfied_partially': 'Other',
    'rd_irt_forgotten_weapons': 'Other',
    'rd_irt_extra_passanger_car': 'Other',
    'rd_irt_mental_health': 'Unintentional_health_damage',
    'rd_irt_forgotten_medicine': 'Other',
    'rd_irt_verbal_altercation_leaving_in_danger': 'Threat',
    'rd_irt_verbal_altercation_hold_for_payment': 'Physical_assault_reports',
    'rd_irt_urgent_traffic_stop': 'Police_involvement',
    'rd_irt_missing_person': 'Missing_person',
    'rd_irt_legal_issue': 'Other',
    'rd_irt_sos': 'Other',
    'rd_irt_sos_not_reached': 'Other',
    'rd_irt_threat_terrorism': 'PR_critical_case',
    'rd_irt_legal_issue_satisfied': 'Other',
    'rd_irt_request': 'Other',
    'rd_irt_accident_without_trip': 'Road_accident_reports',
    'rd_irt_sexual_misconduct': 'Sexual_misconduct_reports',
    'rd_irt': 'Other',
    'rd_irt_non_call': 'Other',
    'rd_irt_accident_compensation': 'Other',
    'rd_irt_sexual_misconduct_indecent_exposure': 'Sexual_misconduct_reports',
    'rd_irt_heist': 'Theft',
    'rd_irt_verbal_altercation_without_trip_third_parties_without_physical_altercation': 'Verbal_altercation_reports',
    'rd_irt_smell_of_substances': 'Other',
    'rd_irt_verbal_altercation_without_trip_third_parties': 'Verbal_altercation_reports',
    'rd_irt_verbal_altercation_third_parties_without_physical_altercation': 'Verbal_altercation_reports',
    'rd_irt_not_urgent_request': 'Other',
    'rd_irt_verbal_altercation_major': 'Verbal_altercation_reports',
    'rd_irt_physical_altercation_used_weapons': 'Threat',
    'rd_irt_physical_altercation_third_parties': 'Physical_assault_reports',
    'rd_irt_physical_altercation_physical_assault': 'Physical_assault_reports',
    'rd_irt_verbal_altercation_threatended_weapons': 'Threat',
    'rd_irt_health': 'Unintentional_health_damage',
    'rd_irt_health_client': 'Unintentional_health_damage',
    'rd_irt_missing_rider': 'Missing_person',
    'rd_irt_accident': 'Road_accident_reports',
    'rd_irt_discrimination': 'Verbal_altercation_reports',
    'rd_irt_health_driver': 'Unintentional_health_damage',
    'rd_irt_legal_issue_managers_satisfied': 'Other',
    'rd_irt_legal_issue_managers_refuse': 'Other',
    'rd_irt_accident_before_boarding': 'Road_accident_reports',
    'rd_irt_missing_driver': 'Missing_person',
    'rd_irt_theft': 'Theft',
    'rd_irt_physical_altercation_damage': 'Other',
    'rd_irt_verbal_altercation_weapons_in_car': 'Threat',
    'rd_irt_traffic_violation': 'Reckless driving reports',
    'rd_irt_dangerous_driving_drug_alcohol': 'Reckless driving reports',
    'rd_irt_fatality': 'PR_critical_case',
    'rd_irt_verbal_altercation_kidnapping': 'Physical_assault_reports',
    'closed_by_merge': 'Other',
    'rd_irt_more_details': 'Other',
    'rd_irt_fraud': 'Other',
    'rd_irt_dangerous_driving_affected_animal': 'Road_accident_reports',
    'rd_irt_dangerous_driving_affected_animal_without_trip': 'Road_accident_reports',
    'rd_irt_verbal_altercation_blogger_driver': 'PR_critical_case',
    'rd_irt_verbal_altercation_with_taxi_company': 'Verbal_altercation_reports',
    'rd_irt_health_was_ill': 'Other',
    'rd_irt_verbal_altercation_threat_intimidation_user': 'Threat',
    'rd_irt_support_negative_feedback': 'Other',
    'rd_irt_verbal_altercation_without_trip_gas_smell': 'Verbal_altercation_reports',
    'rd_irt_threat_arrive_office': 'Threat',
    'rd_irt_threat_arrive_office_driver': 'Threat',
    'rd_irt_threat_arrive_office_user': 'Threat',
    'rd_irt_threat_suicide': 'Threat',
    'rd_irt_threat_suicide_driver': 'Threat',
    'rd_irt_threat_suicide_user': 'Threat',
    'rd_irt_threat_terrorism_driver': 'PR_critical_case',
    'rd_irt_threat_terrorism_user': 'PR_critical_case',
    'rd_irt_pr': 'PR_critical_case',
    'rd_irt_verbal_altercation_conflict_between_passengers': 'Verbal_altercation_reports',
    'rd_irt_verbal_altercation_child_taken_away': 'Physical_assault_reports',
    'rd_irt_second_contact': 'Threat',
    'rd_irt_good_deed': 'Other',
    'rd_irt_premium': 'Other',
    'rd_irt_accident_non_insurance': 'Other',
    'rd_irt_accident_intl': 'Other',
    'rd_irt_wrong_service': 'Other',
    'rd_irt_accessibility': 'Other',
    'rd_irt_accessibility_general_question': 'Other',
    'rd_irt_accessibility_financial_issue': 'Other',
    'rd_irt_accessibility_feedback_driver': 'Other',
    'rd_irt_accessibility_lost_item': 'Other',
    'rd_irt_health_incorrect_conversations': 'Inappropriate_conversations',
    'rd_irt_physical_altercation_soft': 'Physical_assault_reports',
    'rd_irt_physical_altercation_hard': 'Physical_assault_reports',
    'rd_irt_employee_complaint': 'Other'
};

DRIVER_GO_TAGS = {
    'dr_complaint_irt_not_confirmed': 'Other',
    'dr_complaint_irt_from_driver_arms': 'Threat',
    'dr_complaint_irt_from_driver_physical_abuse': 'Physical_assault_reports',
    'dr_complaint_irt_altercation_incorrect_conversations': 'Inappropriate_conversations',
    'dr_complaint_irt_altercation_conflict_third_parties': 'Verbal_altercation_reports',
    'dr_complaint_irt_driver_detained_police': 'Police_involvement',
    'dr_complaint_irt_rider_detained_police': 'Police_involvement',
    'dr_irt_accident_without_order': 'Road_accident_reports',
    'dr_complaint_irt_pdd_encumbrance': 'Unintentional_health_damage',
    'dr_complaint_irt_spam': 'Other',
    'dr_complaint_irt_forgotten_weapons': 'Other',
    'dr_complaint_irt': 'Other',
    'irt_request_from_police': 'Police_involvement',
    'dr_complaint_irt_theft': 'Theft',
    'dr_complaint_irt_discriminatory_comments': 'Verbal_altercation_reports',
    'dr_complaint_irt_sexual_misconduct': 'Sexual_misconduct_reports',
    'dr_complaint_irt_sexual_misconduct_inappropriate_behavior': 'Physical_assault_reports',
    'dr_complaint_irt_sexual_misconduct_indecent_exposure': 'Sexual_misconduct_reports',
    'dr_complaint_irt_sexual_misconduct_sexual_assault': 'Physical_assault_reports',
    'dr_complaint_irt_sexual_misconduct_rape': 'PR_critical_case',
    'dr_complaint_irt_altercation': 'Other',
    'dr_complaint_irt_verbal_altercation_major': 'Verbal_altercation_reports',
    'dr_complaint_irt_fatality': 'PR_critical_case',
    'dr_irt_accident': 'Road_accident_reports',
    'irt_health': 'Unintentional_health_damage',
    'irt_health_client': 'Unintentional_health_damage',
    'irt_health_driver': 'Unintentional_health_damage',
    'dr_complaint_irt_physical_altercation_physical_assault': 'Physical_assault_reports',
    'dr_complaint_irt_physical_altercation_damage': 'Threat',
    'dr_complaint_irt_verbal_altercation_stalking': 'Threat',
    'dr_complaint_irt_inappropriate_contact_after_trip_calls_or_messages': 'Threat',
    'dr_complaint_irt_physical_altercation_used_weapons': 'Threat',
    'dr_complaint_irt_verbal_altercation_threatended_weapons': 'Threat',
    'dr_complaint_irt_verbal_altercation_weapons_in_car': 'Threat',
    'dr_complaint_irt_verbal_altercation_threat_intimidation': 'Threat',
    'dr_complaint_irt_altercation_conflict_without_order': 'Verbal_altercation_reports',
    'dr_complaint_irt_missing_passenger': 'Missing_person',
    'dr_complaint_irt_missing_driver': 'Missing_person',
    'dr_complaint_irt_passenger_made_emergency': 'Threat',
    'dr_complaint_irt_threats_arrive_office': 'Threat',
    'dr_complaint_irt_verbal_altercation_robbery': 'Physical_assault_reports',
    'dr_complaint_irt_verbal_altercation_forgotten_drugs': 'Other',
    'dr_complaint_irt_duplicate': 'Other',
    'dr_complaint_irt_from_driver': 'Other',
    'dr_complaint_irt_theft_phone_fraud': 'Other',
    'dr_complaint_irt_threat_to_passengers': 'Threat',
    'dr_complaint_irt_threats_terrorist_attack': 'PR_critical_case',
    'dr_complaint_irt_threat_of_a_strike': 'PR_critical_case',
    'dr_complaint_irt_threat_suicide': 'PR_critical_case',
    'dr_complaint_irt_from_passenger_threat_suicide': 'PR_critical_case',
    'dr_complaint_irt_from_passenger_threats_terrorist_attack': 'PR_critical_case',
    'dr_complaint_irt_pr': 'PR_critical_case',
    'dr_irt_accident_before_boarding': 'Road_accident_reports',
    'dr_irt_accident_insurance': 'Road_accident_reports',
    'dr_irt_accident_inappropriate_treatment': 'Other',
    'dr_irt_accident_duplicate': 'Other',
    'dr_irt_good_deed': 'Other',
    'dr_complaint_irt_insurance': 'Other',
    'dr_complaint_irt_insurance_physical_assault': 'Physical_assault_reports',
    'dr_complaint_irt_forgotten_medicine': 'Other',
    'dr_complaint_irt_atipical_freight': 'Other',
    'dr_irt_accident_not_insurance': 'Road_accident_reports'
};